replicaCount: 1

image:
  repository: northamerica-northeast1-docker.pkg.dev/phx-01hnapr4ab4/foresight/frontend
  pullPolicy: Always
  tag: latest

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

env:
  DATABASE_URL: "file:/tmp/db.sqlite"
  NEXTAUTH_SECRET: "demo"
  NEXTAUTH_URL: "demo"
  DISCORD_CLIENT_ID: "demo"
  DISCORD_CLIENT_SECRET: "demo"
  NEO4J_USERNAME: "neo4j"
  NEO4J_PASSWORD: "phac@2024"
  NEO4J_URL: "bolt://35.203.10.81:7687"
