#!/bin/bash

python pipeline/cluster-news-articles.py datasets datasets/country-codes.tsv 2019-12-01 cuda
python pipeline/cluster-news-articles.py datasets datasets/country-codes.tsv 2019-12-02 cuda
python pipeline/cluster-news-articles.py datasets datasets/country-codes.tsv 2019-12-03 cuda
python pipeline/cluster-news-articles.py datasets datasets/country-codes.tsv 2019-12-04 cuda
python pipeline/cluster-news-articles.py datasets datasets/country-codes.tsv 2019-12-05 cuda
python pipeline/cluster-news-articles.py datasets datasets/country-codes.tsv 2019-12-06 cuda
python pipeline/cluster-news-articles.py datasets datasets/country-codes.tsv 2019-12-07 cuda
python pipeline/cluster-news-articles.py datasets datasets/country-codes.tsv 2019-12-08 cuda
python pipeline/cluster-news-articles.py datasets datasets/country-codes.tsv 2019-12-09 cuda
python pipeline/cluster-news-articles.py datasets datasets/country-codes.tsv 2019-12-10 cuda
python pipeline/cluster-news-articles.py datasets datasets/country-codes.tsv 2019-12-11 cuda
python pipeline/cluster-news-articles.py datasets datasets/country-codes.tsv 2019-12-12 cuda
python pipeline/cluster-news-articles.py datasets datasets/country-codes.tsv 2019-12-13 cuda
python pipeline/cluster-news-articles.py datasets datasets/country-codes.tsv 2019-12-14 cuda
python pipeline/cluster-news-articles.py datasets datasets/country-codes.tsv 2019-12-15 cuda
python pipeline/cluster-news-articles.py datasets datasets/country-codes.tsv 2019-12-16 cuda
python pipeline/cluster-news-articles.py datasets datasets/country-codes.tsv 2019-12-17 cuda
python pipeline/cluster-news-articles.py datasets datasets/country-codes.tsv 2019-12-18 cuda
python pipeline/cluster-news-articles.py datasets datasets/country-codes.tsv 2019-12-19 cuda
python pipeline/cluster-news-articles.py datasets datasets/country-codes.tsv 2019-12-20 cuda
python pipeline/cluster-news-articles.py datasets datasets/country-codes.tsv 2019-12-21 cuda
python pipeline/cluster-news-articles.py datasets datasets/country-codes.tsv 2019-12-22 cuda
python pipeline/cluster-news-articles.py datasets datasets/country-codes.tsv 2019-12-23 cuda
python pipeline/cluster-news-articles.py datasets datasets/country-codes.tsv 2019-12-24 cuda
python pipeline/cluster-news-articles.py datasets datasets/country-codes.tsv 2019-12-25 cuda
python pipeline/cluster-news-articles.py datasets datasets/country-codes.tsv 2019-12-26 cuda
python pipeline/cluster-news-articles.py datasets datasets/country-codes.tsv 2019-12-27 cuda
python pipeline/cluster-news-articles.py datasets datasets/country-codes.tsv 2019-12-28 cuda
python pipeline/cluster-news-articles.py datasets datasets/country-codes.tsv 2019-12-29 cuda
python pipeline/cluster-news-articles.py datasets datasets/country-codes.tsv 2019-12-30 cuda
python pipeline/cluster-news-articles.py datasets datasets/country-codes.tsv 2019-12-31 cuda
