apiVersion: apps/v1
kind: Deployment
metadata:
  name: neodash-designer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neodash-designer
  template:
    metadata:
      labels:
        app: neodash-designer
        version: v1
    spec:
      containers:
      - name: neodash-designer
        image: nielsdejong/neodash:{{ .Values.neodash.version }}
        ports:
        - containerPort: 5005
        env:
          - name: standaloneHost
            value: "bolt.neo4j.foresight-serum.phac-aspc.alpha.canada.ca"
      restartPolicy: Always