apiVersion: v1
kind: Secret
metadata:
  name: neo4j-secret
type: Opaque
data:
  NEO4J_USERNAME: "{{ default "" .Values.neo4jSecret.NEO4J_USERNAME | b64enc }}"
  NEO4J_PASSWORD: "{{ default "" .Values.neo4jSecret.NEO4J_PASSWORD | b64enc }}"