apiVersion: v1
kind: Service
metadata:
  name: neo4j
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: 7474
    - name: https
      port: {{ .Values.service.httpsPort }}
      targetPort: 7473
    - name: tcp-bolt
      port: {{ .Values.service.boltPort }}
      targetPort: 7687
  selector:
    app: neo4j